version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=trivia_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d trivia_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    volumes:
      - .:/app
    command: /opt/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy

  test:
    build: .
    volumes:
      - .:/app
    # Ejecuta los tests usando el python del entorno virtual
    command: /opt/venv/bin/pytest -v
    depends_on:
      db:
        condition: service_healthy
        
volumes:
  postgres_data: