version: "3.8"

services:
  web:
    build: .
    container_name: trivia_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/trivia_db
      - SECRET_KEY=mysecretkey

  db:
    image: postgres:13
    container_name: trivia_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trivia_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
